/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/revue_subscribers": {
    get: {
      parameters: {
        query: {
          email?: parameters["rowFilter.revue_subscribers.email"];
          first_name?: parameters["rowFilter.revue_subscribers.first_name"];
          last_name?: parameters["rowFilter.revue_subscribers.last_name"];
          created_at?: parameters["rowFilter.revue_subscribers.created_at"];
          /** the time at which the subscriber was synced to convertkit */
          convertkit_synced_at?: parameters["rowFilter.revue_subscribers.convertkit_synced_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["revue_subscribers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** revue_subscribers */
          revue_subscribers?: definitions["revue_subscribers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          email?: parameters["rowFilter.revue_subscribers.email"];
          first_name?: parameters["rowFilter.revue_subscribers.first_name"];
          last_name?: parameters["rowFilter.revue_subscribers.last_name"];
          created_at?: parameters["rowFilter.revue_subscribers.created_at"];
          /** the time at which the subscriber was synced to convertkit */
          convertkit_synced_at?: parameters["rowFilter.revue_subscribers.convertkit_synced_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          email?: parameters["rowFilter.revue_subscribers.email"];
          first_name?: parameters["rowFilter.revue_subscribers.first_name"];
          last_name?: parameters["rowFilter.revue_subscribers.last_name"];
          created_at?: parameters["rowFilter.revue_subscribers.created_at"];
          /** the time at which the subscriber was synced to convertkit */
          convertkit_synced_at?: parameters["rowFilter.revue_subscribers.convertkit_synced_at"];
        };
        body: {
          /** revue_subscribers */
          revue_subscribers?: definitions["revue_subscribers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  revue_subscribers: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    email: string;
    first_name?: string;
    last_name?: string;
    created_at?: string;
    /** the time at which the subscriber was synced to convertkit */
    convertkit_synced_at?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** revue_subscribers */
  "body.revue_subscribers": definitions["revue_subscribers"];
  "rowFilter.revue_subscribers.email": string;
  "rowFilter.revue_subscribers.first_name": string;
  "rowFilter.revue_subscribers.last_name": string;
  "rowFilter.revue_subscribers.created_at": string;
  /** the time at which the subscriber was synced to convertkit */
  "rowFilter.revue_subscribers.convertkit_synced_at": string;
}

export interface operations {}

export interface external {}
