
name: sync-convertkit-5-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://revue-convertkit-sync.vercel.app/api/supabase-to-convertkit' \
